"""
models/question.py — Question Table
=====================================
One row per question asked during a viva session.

Each question is generated by the Gemini AI (Phase 2) and saved here so that:
  - The answer evaluator can compare the student's response to the expected answer
  - The report can show which questions were asked and how they were answered
  - Adaptive logic can look back at previous difficulty levels

Relationships:
  - Belongs to one Session  (session_id → sessions.id)
  - Has one Score           (scores.question_id → questions.id)
"""

from sqlalchemy import Column, Text, Integer, DateTime
from datetime import datetime
from app.core.database import Base


class Question(Base):
    __tablename__ = "questions"

    # Unique question ID — generated as a UUID string
    id = Column(Text, primary_key=True)

    # Foreign key: which session this question belongs to
    session_id = Column(Text, nullable=False)

    # The actual question text shown/spoken to the student
    question_text = Column(Text, nullable=False)

    # The ideal/model answer generated by Gemini alongside the question.
    # Used by the semantic scorer to evaluate how close the student's answer was.
    expected_answer = Column(Text, nullable=True)

    # JSON array of important domain keywords for this question.
    # Example: '["stack", "LIFO", "push", "pop"]'
    # Used by the keyword scorer to check if the student mentioned key terms.
    key_keywords = Column(Text, nullable=True)   # JSON array as string

    # JSON array of key conceptual points the answer should cover.
    # Example: '["define stack", "explain LIFO", "give example"]'
    # Used by the depth and completeness scorers.
    key_points = Column(Text, nullable=True)     # JSON array as string

    # Difficulty level of this question on a scale of 1 (easy) to 5 (hard).
    # The adaptive logic adjusts this based on the student's previous scores.
    level = Column(Integer, default=1)

    # Which topic this question was generated for
    topic = Column(Text, nullable=True)

    # Timestamp when this question was asked (UTC)
    asked_at = Column(DateTime, default=datetime.utcnow)
