"""
models/score.py — Score Table
================================
One row per question answered. Stores the student's raw answer and all
individual scorer outputs, plus the final weighted score.

The final_score is calculated by answer_evaluator.py (Phase 2) using
a weighted formula across the 5 pillar scores:
    final = (semantic * 0.35) + (keyword * 0.25) + (depth * 0.20)
           + (completeness * 0.10) + (confidence * 0.10)

All score columns are floats in the range 0.0–1.0 (normalised per scorer).

Relationships:
  - Belongs to one Question  (question_id → questions.id)
  - Belongs to one Session   (session_id → sessions.id)
"""

from sqlalchemy import Column, Text, Float
from app.core.database import Base


class Score(Base):
    __tablename__ = "scores"

    # Unique score record ID — generated as a UUID string
    id = Column(Text, primary_key=True)

    # Foreign key: which question this score belongs to
    question_id = Column(Text, nullable=False)

    # Foreign key: which session this score belongs to (denormalised for easy report queries)
    session_id = Column(Text, nullable=False)

    # The raw text of what the student actually said/typed
    student_answer = Column(Text, nullable=True)

    # Pillar 1 — Semantic similarity score (cosine similarity via sentence-transformers).
    # Measures how closely the student's answer means the same as the expected answer.
    semantic_score = Column(Float, nullable=True)

    # Pillar 2 — Keyword coverage score.
    # Fraction of key_keywords the student's answer contained.
    keyword_score = Column(Float, nullable=True)

    # Pillar 3 — Answer depth score.
    # Measures how thoroughly the student explained their answer.
    depth_score = Column(Float, nullable=True)

    # Pillar 4 — Completeness score.
    # Fraction of key_points the student's answer covered.
    completeness_score = Column(Float, nullable=True)

    # Pillar 5 — Confidence score.
    # Derived from voice analysis: speech pace, pauses, filler words.
    confidence_score = Column(Float, nullable=True)

    # The final weighted score combining all 5 pillars (see formula above)
    final_score = Column(Float, nullable=True)

    # Human-readable explanation of why the student got the depth_score they did.
    # Generated by Gemini as part of the scoring response.
    depth_reason = Column(Text, nullable=True)

    # Human-readable explanation of the completeness_score
    completeness_reason = Column(Text, nullable=True)

    # The topic that was being examined when this answer was given.
    # Denormalised here so score_calculator can group by topic without a JOIN.
    topic = Column(Text, nullable=True)

    # What the adaptive engine decided after seeing this score:
    # "level_up" | "follow_up" | "checkpoint" | "topic_complete" | "session_end" etc.
    adaptive_decision = Column(Text, nullable=True)
