"""
models/student.py — Student Table
===================================
Stores one row per registered student (one-time registration).

A student must register before taking any viva. During registration:
  - Their name and email are saved
  - A face photo is captured, encoded to a binary vector, and saved as face_encoding
  - This encoding is used later to verify the student's identity at viva start

Relationships (not enforced by SQLite foreign keys here, but by logic):
  - One student can have many sessions (sessions.student_id → students.id)
"""

from sqlalchemy import Column, Text, DateTime
from sqlalchemy.dialects.sqlite import BLOB
from datetime import datetime
from app.core.database import Base


class Student(Base):
    __tablename__ = "students"

    # Unique student ID — generated as a UUID string when they register
    id = Column(Text, primary_key=True)

    # Full name as entered during registration
    name = Column(Text, nullable=False)

    # Email address — used as a unique identifier for login
    email = Column(Text, nullable=False)

    # Binary face encoding from the registration photo.
    # Stored as a BLOB (raw bytes). Generated by the face_recognition library.
    # Used during verify-face to confirm the student sitting at the camera
    # is the same person who registered. Nullable until they upload a photo.
    face_encoding = Column(BLOB, nullable=True)

    # Timestamp of when the student account was created (UTC)
    created_at = Column(DateTime, default=datetime.utcnow)
