"""
main.py — FastAPI Application Entry Point
==========================================
This is the first file that runs when the backend server starts.
It does 4 things in order:
  1. Creates the FastAPI app instance
  2. Configures CORS so the React frontend (port 5173) can call this API (port 8000)
  3. Creates all SQLite database tables (safe to run on every restart — skips existing tables)
  4. Registers all API route groups so their endpoints are accessible

To start the server (from the backend/ directory):
    .\\venv\\Scripts\\uvicorn.exe main:app --reload

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.core.database import engine, Base

# Import all model files so SQLAlchemy registers their table definitions
# before we call create_all(). Without these imports, Base.metadata is empty
# and no tables would be created.
from app.models import student, session, question, score, integrity_flag

# Import all route groups. Each module handles a different part of the API.
from app.api import auth, topics, session as session_router, viva, cv, report

# Create the main FastAPI application instance.
# 'title' appears in the Swagger UI at /docs.
app = FastAPI(title="Automatic Viva Taker API")

# CORS (Cross-Origin Resource Sharing) middleware.
# Browsers block requests between different origins by default.
# This tells the browser that http://localhost:5173 (React/Vite dev server)
# is allowed to call http://localhost:8000 (this FastAPI server).
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,                   # Allow cookies/auth headers
    allow_methods=["*"],                      # Allow GET, POST, PUT, DELETE, etc.
    allow_headers=["*"],                      # Allow any request headers
)

# Create all 5 database tables defined in the models folder.
# SQLAlchemy looks at all classes that inherit from Base and creates their tables.
# If a table already exists, it skips creation — no data loss on restart.
Base.metadata.create_all(bind=engine)

# Register all route groups with their URL prefixes.
# Each router was created in its own file under app/api/.
#   auth          -> /api/auth/*          (register, login, face verification)
#   topics        -> /api/topics          (list all available exam topics)
#   session       -> /api/session/*       (start, end, switch topic)
#   viva          -> /api/viva/*          (get next question, submit answer)
#   cv            -> /api/cv/*            (send webcam frame for proctoring analysis)
#   report        -> /api/report/*        (get score report, download PDF)
app.include_router(auth.router)
app.include_router(topics.router)
app.include_router(session_router.router)
app.include_router(viva.router)
app.include_router(cv.router)
app.include_router(report.router)


@app.get("/")
def root():
    """Health check — confirms the backend is running. Visit http://localhost:8000/"""
    return {"status": "Automatic Viva Taker API is running"}
