"""
pillar3_assessment/depth_scorer.py — Depth & Completeness Scorer (LLM)
========================================================================
Uses Gemini to evaluate two subjective dimensions of the student's answer:

  depth_score       — How thoroughly did the student explain their answer?
                      Did they go beyond surface definitions to show real understanding?

  completeness_score — Did the student cover all the key conceptual points?
                       Measured against key_points from the question generator.

These two scores are evaluated together in a single Gemini API call (LLM Call 2)
because both require understanding context, not just string matching.

Output dict:
    {
        "depth_score":           7.5,   # float 0.0–10.0
        "completeness_score":    6.0,   # float 0.0–10.0
        "depth_reason":          "Student explained the concept well but did not...",
        "completeness_reason":   "Covered 3 of 4 key points. Missing: ..."
    }

Usage:
    from app.services.pillar3_assessment.depth_scorer import score_depth_completeness
    result = score_depth_completeness(question, expected_answer, student_answer, key_points)
"""

import json
import re
from google import genai

from app.core.config import GEMINI_API_KEY


def score_depth_completeness(
    question: str,
    expected_answer: str,
    student_answer: str,
    key_points: list,
) -> dict:
    """
    Use Gemini to evaluate depth and completeness of the student's answer.

    Args:
        question:        The exam question that was asked.
        expected_answer: The ideal answer generated by question_generator.py.
        student_answer:  The raw text of what the student said/typed.
        key_points:      List of core concepts the answer should cover.

    Returns:
        Dict with keys:
            depth_score (float 0–10), completeness_score (float 0–10),
            depth_reason (str), completeness_reason (str)

    Raises:
        RuntimeError: If GEMINI_API_KEY is missing.
        ValueError:   If Gemini returns invalid JSON.
    """
    # Handle empty answer without making an API call
    if not student_answer or not student_answer.strip():
        return {
            "depth_score": 0.0,
            "completeness_score": 0.0,
            "depth_reason": "No answer was provided.",
            "completeness_reason": "No answer was provided. All key points missed.",
        }

    api_key = GEMINI_API_KEY.strip()
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY is not set in backend/.env")

    client = genai.Client(api_key=api_key)

    # Format key_points as a numbered list for the prompt
    key_points_text = "\n".join(f"  {i+1}. {pt}" for i, pt in enumerate(key_points))

    prompt = f"""You are an examiner evaluating a student's oral exam answer.

Question asked: {question}

Expected ideal answer: {expected_answer}

Key points the answer should cover:
{key_points_text}

Student's actual answer: {student_answer}

Evaluate the student's answer on TWO dimensions:

1. DEPTH (0–10): How thoroughly did the student explain? Did they demonstrate real understanding beyond just naming terms? Did they explain WHY or HOW, not just WHAT?
   - 9–10: Excellent depth, explained mechanisms and implications
   - 7–8:  Good depth, explained well with minor gaps
   - 5–6:  Surface level, correct but not explained thoroughly
   - 3–4:  Minimal explanation, mostly named terms without explanation
   - 0–2:  No meaningful explanation

2. COMPLETENESS (0–10): How many of the key points did the student cover?
   - 10: All key points covered
   - 7–9: Most key points covered
   - 4–6: About half the key points covered
   - 1–3: Very few key points covered
   - 0: No key points covered

Respond with ONLY a JSON object (no markdown, no code blocks):
{{
    "depth_score": <number 0-10>,
    "completeness_score": <number 0-10>,
    "depth_reason": "<one sentence explaining the depth score>",
    "completeness_reason": "<one sentence listing which key points were covered and which were missing>"
}}"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
    )
    raw_text = response.text.strip()

    # Strip markdown fences if Gemini wraps the response
    raw_text = re.sub(r"^```(?:json)?\s*", "", raw_text)
    raw_text = re.sub(r"\s*```$", "", raw_text)

    try:
        result = json.loads(raw_text)
    except json.JSONDecodeError as e:
        raise ValueError(
            f"Gemini returned non-JSON response.\n"
            f"Raw: {raw_text}\nError: {e}"
        )

    # Validate and clamp scores to valid range
    required_keys = {"depth_score", "completeness_score", "depth_reason", "completeness_reason"}
    missing = required_keys - set(result.keys())
    if missing:
        raise ValueError(f"Gemini response missing keys: {missing}")

    result["depth_score"] = round(max(0.0, min(10.0, float(result["depth_score"]))), 2)
    result["completeness_score"] = round(max(0.0, min(10.0, float(result["completeness_score"]))), 2)

    return result


# ─────────────────────────────────────────────────────────────────────────────
# Standalone test:
#   cd backend
#   .\venv\Scripts\python.exe app/services/pillar3_assessment/depth_scorer.py
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    QUESTION = "What is a binary search tree and how does it enable efficient search?"
    EXPECTED = (
        "A binary search tree (BST) is a tree where each node has at most two children. "
        "For every node, the left subtree contains only values smaller than the node, "
        "and the right subtree contains only values larger. This ordering property allows "
        "binary search: at each node, we eliminate half the remaining tree, giving "
        "O(log n) average search time. BSTs are used in databases, symbol tables, and "
        "ordered sets."
    )
    KEY_POINTS = [
        "define BST structure (nodes with up to 2 children)",
        "explain left < root < right ordering property",
        "explain how ordering enables binary search",
        "state O(log n) average time complexity",
        "give a use case",
    ]

    test_cases = [
        (
            "STRONG",
            "A binary search tree is a hierarchical data structure where each node "
            "has at most two children. The key invariant is that all nodes in the left "
            "subtree have values less than the current node, and all nodes in the right "
            "subtree have values greater. This property means we can search by repeatedly "
            "comparing the target to the current node and going left or right, which "
            "eliminates half the tree each time — giving O(log n) average time. BSTs "
            "are commonly used in implementing ordered dictionaries and range queries.",
        ),
        (
            "PARTIAL",
            "A BST is a tree where the left side has smaller numbers and the right side "
            "has bigger numbers. This makes it easier to find things.",
        ),
        (
            "WRONG",
            "Binary search is an algorithm that searches a sorted array by checking "
            "the middle element and discarding half the array each time.",
        ),
        (
            "EMPTY",
            "",
        ),
    ]

    print("=" * 60)
    print("Testing depth_scorer.py")
    print("=" * 60)

    for label, student_answer in test_cases:
        print(f"\n  [{label}]")
        try:
            result = score_depth_completeness(QUESTION, EXPECTED, student_answer, KEY_POINTS)
            print(f"  Depth Score        : {result['depth_score']} / 10.0")
            print(f"  Completeness Score : {result['completeness_score']} / 10.0")
            print(f"  Depth Reason       : {result['depth_reason']}")
            print(f"  Completeness Reason: {result['completeness_reason']}")
            print(f"  STATUS: PASS ✓")
        except Exception as e:
            print(f"  STATUS: FAIL ✗ — {e}")

    print("\n" + "=" * 60)
